# BX_bevelx/BX_build_vmesh.py
from __future__ import annotations

from dataclasses import dataclass
from typing import Iterable, List, Optional

from BX_bevelx.BX_constants import (
    M_ADJ,
    M_NONE,
    M_POLY,
)
from BX_bevelx.BX_types import (
    BevelParams,
    BevVert,
    BoundVert,
    NewVert,
    VMesh,
)


# ---------------------------------------------------------------------------
# Generated topology records
# ---------------------------------------------------------------------------

@dataclass
class VMeshPolygon:
    """
    Small internal record for polygons generated by build_vmesh().

    This is not a BevelX transaction face and it is not a Maya face yet.
    It is the Python-side equivalent of Blender having created geometry during
    the VMesh phase. Final mesh emission happens later.
    """

    newverts: List[NewVert]
    owner: Optional[BevVert] = None
    label: str = "VMESH"


# ---------------------------------------------------------------------------
# Ring helpers
# ---------------------------------------------------------------------------

def boundverts_from_vmesh(vm: VMesh) -> List[BoundVert]:
    """
    Return BoundVerts in circular order.
    """

    if vm is None:
        return []

    if vm.boundstart is None:
        return []

    return list(vm.iter_boundverts())


def boundvert_newverts(vm: VMesh) -> List[NewVert]:
    """
    Return boundary NewVerts in circular BoundVert order.
    """

    return [boundvert.nv for boundvert in boundverts_from_vmesh(vm)]


# ---------------------------------------------------------------------------
# Mesh-kind selection
# ---------------------------------------------------------------------------

def classify_vmesh_kind(bevvert: BevVert,
                        params: BevelParams) -> str:
    """
    Initial Python port of Blender VMesh kind selection.

    This is intentionally conservative:
        - no boundary verts -> M_NONE
        - selcount == 2 and boundary count == 2 -> Blender weld/no-vmesh case
        - seg == 1 and count >= 3 -> M_POLY
        - seg > 1 and count >= 3 -> M_ADJ placeholder for next phase

    Blender has more branches later, including cutoff/tri-fan behavior. Those
    belong in this file as the port progresses, not in transaction/rebuild code.
    """

    vm = bevvert.vmesh

    if vm is None:
        return M_NONE

    count = vm.count
    seg = max(1, int(params.seg))

    if count == 0:
        return M_NONE

    # Blender weld/no-vmesh situation.
    if bevvert.selcount == 2 and count == 2:
        return M_NONE

    if count >= 3 and seg == 1:
        return M_POLY

    if count >= 3:
        return M_ADJ

    return M_NONE


def assign_vmesh_kind(bevvert: BevVert,
                      params: BevelParams) -> str:
    """
    Assign mesh_kind and common segment count to BevVert.vmesh.
    """

    if bevvert.vmesh is None:
        bevvert.vmesh = VMesh()

    vm = bevvert.vmesh
    vm.seg = max(1, int(params.seg))
    vm.mesh_kind = classify_vmesh_kind(bevvert, params)

    return vm.mesh_kind


# ---------------------------------------------------------------------------
# VMesh construction
# ---------------------------------------------------------------------------

def clear_vmesh_generated_data(vm: VMesh):
    """
    Clear generated VMesh data from a previous run.
    """

    vm.mesh = []
    vm.generated_polygons = []


def build_poly_vmesh(bevvert: BevVert,
                     params: BevelParams) -> List[VMeshPolygon]:
    """
    Build the simple M_POLY vertex mesh.

    For seg == 1, the boundary ring itself is the vertex mesh polygon. Blender
    creates mesh geometry directly; this Python port stores the generated
    polygon as NewVert references for later mesh emission.
    """

    vm = bevvert.vmesh
    newverts = boundvert_newverts(vm)

    if len(newverts) < 3:
        return []

    polygon = VMeshPolygon(
        newverts=newverts,
        owner=bevvert,
        label="VMESH_POLY",
    )

    return [polygon]


def build_adj_vmesh_placeholder(bevvert: BevVert,
                                params: BevelParams) -> List[VMeshPolygon]:
    """
    Placeholder for Blender M_ADJ VMesh construction.

    This function deliberately does not fake ADJ geometry. It allocates the
    VMesh storage layout so later direct ports of Blender's ADJ construction
    can fill vm.mesh using vm.mesh_vert(i, j, k).
    """

    vm = bevvert.vmesh
    vm.allocate_mesh()

    return []


def build_vmesh_for_bevvert(bevvert: BevVert,
                            params: BevelParams) -> VMesh:
    """
    Build VMesh data for one BevVert.

    Inputs expected to already exist:
        - bevvert.edges
        - bevvert.vmesh.boundstart BoundVert ring

    Outputs stored on bevvert.vmesh:
        - mesh_kind
        - generated_polygons for M_POLY
        - allocated mesh storage for M_ADJ placeholder
    """

    if bevvert.vmesh is None:
        bevvert.vmesh = VMesh()

    vm = bevvert.vmesh
    clear_vmesh_generated_data(vm)

    mesh_kind = assign_vmesh_kind(
        bevvert=bevvert,
        params=params,
    )

    if mesh_kind == M_NONE:
        vm.generated_polygons = []
        return vm

    if mesh_kind == M_POLY:
        vm.generated_polygons = build_poly_vmesh(
            bevvert=bevvert,
            params=params,
        )
        return vm

    if mesh_kind == M_ADJ:
        vm.generated_polygons = build_adj_vmesh_placeholder(
            bevvert=bevvert,
            params=params,
        )
        return vm

    vm.generated_polygons = []
    return vm


def build_vmeshes(params: BevelParams,
                  bevverts: Optional[Iterable[BevVert]] = None) -> BevelParams:
    """
    Build VMesh data for all BevVerts.

    If bevverts is None, use params.vert_hash.values().
    """

    params.normalize()

    if bevverts is None:
        bevverts = params.vert_hash.values()

    for bevvert in bevverts:
        build_vmesh_for_bevvert(
            bevvert=bevvert,
            params=params,
        )

    return params


# ---------------------------------------------------------------------------
# Debug helpers
# ---------------------------------------------------------------------------

def vert_index(vert):
    return getattr(vert, "index", None)


def debug_vmesh_summary(params: BevelParams) -> List[str]:
    """
    Human-readable VMesh state for smoke tests.
    """

    lines = []

    for vert, bevvert in sorted(
        params.vert_hash.items(),
        key=lambda item: getattr(item[0], "index", -1),
    ):
        vm = bevvert.vmesh

        if vm is None:
            lines.append(
                "VMesh vert={0} missing".format(
                    vert_index(bevvert.v),
                )
            )
            continue

        polygon_lengths = [
            len(polygon.newverts)
            for polygon in getattr(vm, "generated_polygons", [])
        ]

        lines.append(
            "VMesh vert={0} selcount={1} edgecount={2} count={3} seg={4} kind={5} polygons={6}".format(
                vert_index(bevvert.v),
                bevvert.selcount,
                bevvert.edgecount,
                vm.count,
                vm.seg,
                vm.mesh_kind,
                polygon_lengths,
            )
        )

    return lines
