# BX_boundary.py
# BevelX boundary vertex construction.
#
# This is our first equivalent of Blender's BoundVert layer.
#
# Current milestone:
# - terminal boundary for one selected edge
# - two boundary verts per endpoint
# - boundary points come from already computed offset rails

from __future__ import print_function


class BX_BoundaryVertex(object):
    """
    Boundary vertex around an original bevel vertex.

    This is a simplified BevelX version of Blender's BoundVert.

    For the current terminal-edge case:
        - one original vertex touched by one selected edge
        - one boundary point per adjacent face rail
    """

    def __init__(self,
                 boundary_id,
                 original_vertex_id,
                 selected_edge_id,
                 face_id,
                 co_world,
                 source="TERMINAL"):
        self.id = boundary_id

        self.original_vertex_id = int(original_vertex_id)
        self.selected_edge_id = int(selected_edge_id)
        self.face_id = int(face_id)

        self.co_world = list(co_world)

        self.source = source

        self.prev = None
        self.next = None

    def __repr__(self):
        prev_id = self.prev.id if self.prev else None
        next_id = self.next.id if self.next else None

        return (
            "BX_BoundaryVertex(id={0}, original_vertex={1}, "
            "edge={2}, face={3}, co={4}, prev={5}, next={6})"
        ).format(
            self.id,
            self.original_vertex_id,
            self.selected_edge_id,
            self.face_id,
            self.co_world,
            prev_id,
            next_id,
        )


def build_terminal_boundaries_for_edge(edge_data, rails, bevel_vertices):
    """
    Build terminal boundary vertices for one selected edge.

    Args:
        edge_data:
            Legacy selected-edge data dictionary.

        rails:
            Rails generated by build_preview_offset_rails().

            Expected:
            [
                {
                    "face_id": int,
                    "normal": [x, y, z],
                    "rail": ([p0], [p1])
                },
                ...
            ]

        bevel_vertices:
            Dictionary:
                {
                    vertex_id: BX_BevelVertex
                }

    Returns:
        {
            vertex_id: [BX_BoundaryVertex, BX_BoundaryVertex]
        }

    Important:
        rail[0] corresponds to edge_v0
        rail[1] corresponds to edge_v1
    """

    if bevel_vertices is None:
        print("[BevelX] Boundary build skipped: no bevel vertices.")
        return {}

    edge_id = edge_data["edge_id"]
    edge_v0, edge_v1 = edge_data["vertex_ids"]

    if edge_v0 not in bevel_vertices or edge_v1 not in bevel_vertices:
        print("[BevelX] Boundary build skipped: selected edge endpoints not in bevel vertices.")
        return {}

    vertex_boundaries = {
        edge_v0: [],
        edge_v1: [],
    }

    for rail_data in rails:
        face_id = rail_data["face_id"]
        rail_p0, rail_p1 = rail_data["rail"]

        boundary_v0 = BX_BoundaryVertex(
            boundary_id="BV{0}_E{1}_F{2}".format(edge_v0, edge_id, face_id),
            original_vertex_id=edge_v0,
            selected_edge_id=edge_id,
            face_id=face_id,
            co_world=rail_p0,
            source="TERMINAL"
        )

        boundary_v1 = BX_BoundaryVertex(
            boundary_id="BV{0}_E{1}_F{2}".format(edge_v1, edge_id, face_id),
            original_vertex_id=edge_v1,
            selected_edge_id=edge_id,
            face_id=face_id,
            co_world=rail_p1,
            source="TERMINAL"
        )

        vertex_boundaries[edge_v0].append(boundary_v0)
        vertex_boundaries[edge_v1].append(boundary_v1)

    for vertex_id, boundary_list in vertex_boundaries.items():
        link_boundary_vertices_cyclic(boundary_list)

        bevel_vertex = bevel_vertices[vertex_id]
        bevel_vertex.boundary_vertices.extend(boundary_list)

    return vertex_boundaries


def link_boundary_vertices_cyclic(boundary_vertices):
    """
    Link boundary vertices as a cyclic list.
    """

    count = len(boundary_vertices)

    if count == 0:
        return

    for i, boundary_vertex in enumerate(boundary_vertices):
        boundary_vertex.prev = boundary_vertices[(i - 1) % count]
        boundary_vertex.next = boundary_vertices[(i + 1) % count]


def debug_print_boundaries(vertex_boundaries):
    """
    Print boundary construction diagnostics.
    """

    total = sum(len(items) for items in vertex_boundaries.values())

    print("[BevelX] BoundaryVertex total: {0}".format(total))

    for vertex_id in sorted(vertex_boundaries.keys()):
        boundary_list = vertex_boundaries[vertex_id]

        print("[BevelX] Boundary for BevelVertex {0}:".format(vertex_id))
        print("[BevelX]   boundary count: {0}".format(len(boundary_list)))

        for i, boundary_vertex in enumerate(boundary_list):
            print("[BevelX]   boundary[{0}]: {1}".format(i, boundary_vertex))

# -----------------------------------------------------------------------------
# Multi-edge boundary classification
# -----------------------------------------------------------------------------
def classify_bevel_vertices_topology(bm, bevel_vertices):
    """
    Classify bevel vertices using topology, not only selected edge count.

    Returns:
        {
            vertex_id: {
                "selected_count": int,
                "kind": str
            }
        }

    Kinds:
        TERMINAL
        CORNER_2
        CHAIN_2
        CORNER_3_PLUS
        NONE
    """

    result = {}

    for vertex_id, bevel_vertex in bevel_vertices.items():
        selected_count = bevel_vertex.selected_count

        if selected_count == 0:
            kind = "NONE"

        elif selected_count == 1:
            kind = "TERMINAL"

        elif selected_count == 2:
            if is_corner_2_vertex(bm, bevel_vertex):
                kind = "CORNER_2"
            else:
                kind = "CHAIN_2"

        elif selected_count == 3:
            kind = "CORNER_3_CAP"

        else:
            kind = "CORNER_3_PLUS"

        result[vertex_id] = {
            "selected_count": selected_count,
            "kind": kind,
        }

    return result


def debug_print_bevel_vertex_topology_classification(bm, bevel_vertices):
    """
    Print topology-aware boundary classification.
    """

    classification = classify_bevel_vertices_topology(
        bm=bm,
        bevel_vertices=bevel_vertices
    )

    print("[BevelX] Bevel vertex topology classification:")

    for vertex_id in sorted(classification.keys()):
        data = classification[vertex_id]

        print("[BevelX]   Vertex {0}: kind={1}, selected_count={2}".format(
            vertex_id,
            data["kind"],
            data["selected_count"]
        ))

    return classification

def classify_bevel_vertices(bevel_vertices):
    """
    Classify bevel vertices by selected edge count.

    Returns:
        {
            vertex_id: {
                "selected_count": int,
                "kind": str
            }
        }

    Kinds:
        TERMINAL
            One selected edge enters this vertex.

        CORNER_2
            Two selected edges meet at this vertex.
            This needs sharp-corner / miter boundary logic.

        CORNER_3_PLUS
            Three or more selected edges meet.
            This will need VMesh/corner cap logic later.

        NONE
            Should normally not happen for affected bevel vertices.
    """

    result = {}

    for vertex_id, bevel_vertex in bevel_vertices.items():
        selected_count = bevel_vertex.selected_count

        if selected_count == 0:
            kind = "NONE"
        elif selected_count == 1:
            kind = "TERMINAL"
        elif selected_count == 2:
            kind = "CORNER_2"
        else:
            kind = "CORNER_3_PLUS"

        result[vertex_id] = {
            "selected_count": selected_count,
            "kind": kind,
        }

    return result


def debug_print_bevel_vertex_classification(bevel_vertices):
    """
    Print selected-edge count classification for each bevel vertex.
    """

    classification = classify_bevel_vertices(bevel_vertices)

    print("[BevelX] Bevel vertex boundary classification:")

    for vertex_id in sorted(classification.keys()):
        data = classification[vertex_id]

        print("[BevelX]   Vertex {0}: kind={1}, selected_count={2}".format(
            vertex_id,
            data["kind"],
            data["selected_count"]
        ))

    return classification


def has_unsupported_multi_edge_vertices(bevel_vertices):
    """
    Return True if the current selected edge set requires unsupported
    boundary modes.

    selected_count == 3 is now routed to first M_TRI_CAP.
    """

    for vertex_id, bevel_vertex in bevel_vertices.items():
        if bevel_vertex.selected_count > 3:
            return True

    return False

def get_unsupported_boundary_reason(bevel_vertices):
    """
    Return a readable reason if the current selection contains unsupported
    boundary cases.

    Supported:
        TERMINAL
        CORNER_2
        CHAIN_2
        CORNER_3_CAP, first simple M_TRI_CAP version

    Unsupported:
        selected_count > 3
    """

    unsupported = []

    for vertex_id in sorted(bevel_vertices.keys()):
        bevel_vertex = bevel_vertices[vertex_id]

        if bevel_vertex.selected_count > 3:
            unsupported.append(
                "vertex {0} has {1} selected edges; full VMesh/corner cap is not implemented yet".format(
                    vertex_id,
                    bevel_vertex.selected_count
                )
            )

    if not unsupported:
        return None

    return "; ".join(unsupported)

def requires_selection_transaction(bevel_vertices):
    """
    Return True when the current bevel cannot be represented as a simple
    one-edge terminal transaction.

    Multi-edge selections and CORNER_2 vertices need one shared
    selection-level transaction.
    """

    classification = classify_bevel_vertices(bevel_vertices)

    for vertex_id, data in classification.items():
        if data["kind"] == "CORNER_2":
            return True

        if data["kind"] == "CORNER_3_PLUS":
            return True

    return False

# -----------------------------------------------------------------------------
# CORNER_2 boundary preview
# -----------------------------------------------------------------------------

def build_boundaries_for_selection(bm, edges_data, rails_by_edge_id, bevel_vertices):
    """
    Build boundary vertices for the current selected edge set.

    Current support:
        - TERMINAL vertices
        - CORNER_2 vertices, preview/debug only

    Returns:
        {
            vertex_id: [BX_BoundaryVertex, ...]
        }
    """

    vertex_boundaries = {}

    edge_data_by_id = {
        edge_data["edge_id"]: edge_data
        for edge_data in edges_data
    }

    for vertex_id, bevel_vertex in bevel_vertices.items():
        if bevel_vertex.selected_count == 1:
            selected_edge_id = bevel_vertex.selected_edges[0]

            edge_data = edge_data_by_id[selected_edge_id]
            rails = rails_by_edge_id[selected_edge_id]

            boundary_list = build_terminal_boundary_for_vertex(
                edge_data=edge_data,
                rails=rails,
                vertex_id=vertex_id
            )

            vertex_boundaries[vertex_id] = boundary_list

        elif bevel_vertex.selected_count == 2:
            if is_corner_2_vertex(bm, bevel_vertex):
                boundary_list = build_corner_2_boundary_for_vertex(
                    bm=bm,
                    bevel_vertex=bevel_vertex,
                    edge_data_by_id=edge_data_by_id,
                    rails_by_edge_id=rails_by_edge_id
                )

                vertex_boundaries[vertex_id] = boundary_list

            else:
                boundary_list = build_chain_2_boundary_for_vertex(
                    bm=bm,
                    bevel_vertex=bevel_vertex,
                    edge_data_by_id=edge_data_by_id,
                    rails_by_edge_id=rails_by_edge_id
                )

                vertex_boundaries[vertex_id] = boundary_list

        elif bevel_vertex.selected_count == 3:
            from BX_boundary import BX_vmesh

            boundary_list = BX_vmesh.build_corner_3_tri_cap_boundary_for_vertex(
                bm=bm,
                bevel_vertex=bevel_vertex,
                edge_data_by_id=edge_data_by_id,
                rails_by_edge_id=rails_by_edge_id,
                boundary_class=BX_BoundaryVertex,
                link_function=link_boundary_vertices_cyclic
            )

            vertex_boundaries[vertex_id] = boundary_list

        else:
            vertex_boundaries[vertex_id] = []

    return vertex_boundaries


def build_terminal_boundary_for_vertex(edge_data, rails, vertex_id):
    """
    Build terminal boundary vertices for only one endpoint of one selected edge.

    This is the per-vertex version of build_terminal_boundaries_for_edge().
    """

    edge_id = edge_data["edge_id"]
    edge_v0, edge_v1 = edge_data["vertex_ids"]

    if vertex_id not in (edge_v0, edge_v1):
        return []

    boundary_list = []

    for rail_data in rails:
        face_id = rail_data["face_id"]
        rail_p0, rail_p1 = rail_data["rail"]

        if vertex_id == edge_v0:
            point = rail_p0
        else:
            point = rail_p1

        boundary_vertex = BX_BoundaryVertex(
            boundary_id="BV{0}_E{1}_F{2}".format(vertex_id, edge_id, face_id),
            original_vertex_id=vertex_id,
            selected_edge_id=edge_id,
            face_id=face_id,
            co_world=point,
            source="TERMINAL"
        )

        boundary_list.append(boundary_vertex)

    link_boundary_vertices_cyclic(boundary_list)

    return boundary_list

# -----------------------------------------------------------------------------
# CHAIN_2 helpers
# -----------------------------------------------------------------------------

def get_common_faces_between_selected_edges(bm, selected_edge_ids):
    """
    Return common faces shared by two selected edges.

    Args:
        bm:
            BX_BMesh.

        selected_edge_ids:
            Exactly two selected edge ids.

    Returns:
        Sorted list of common face ids.
    """

    if len(selected_edge_ids) != 2:
        return []

    edge_a = bm.edges[selected_edge_ids[0]]
    edge_b = bm.edges[selected_edge_ids[1]]

    return sorted(list(set(edge_a.faces).intersection(set(edge_b.faces))))


def is_chain_2_vertex(bm, bevel_vertex):
    """
    Return True when a bevel vertex has two selected edges but those
    selected edges do not share a face.

    This is a through-chain case, not a miter/corner case.
    """

    if bevel_vertex.selected_count != 2:
        return False

    common_faces = get_common_faces_between_selected_edges(
        bm=bm,
        selected_edge_ids=list(bevel_vertex.selected_edges)
    )

    return not common_faces


def is_corner_2_vertex(bm, bevel_vertex):
    """
    Return True when a bevel vertex has two selected edges and those
    selected edges share a face.

    This is the sharp miter/corner case.
    """

    if bevel_vertex.selected_count != 2:
        return False

    common_faces = get_common_faces_between_selected_edges(
        bm=bm,
        selected_edge_ids=list(bevel_vertex.selected_edges)
    )

    return bool(common_faces)


def build_chain_2_boundary_for_vertex(bm,
                                      bevel_vertex,
                                      edge_data_by_id,
                                      rails_by_edge_id):
    """
    Build boundary vertices for a CHAIN_2 vertex.

    CHAIN_2 means:
        - exactly two selected edges touch this vertex
        - the selected edges do NOT share a common face
        - bevel should pass through the vertex
        - no miter point
        - no F_VERT cap
        - no VMesh

    For each selected edge, create one boundary vertex per adjacent face
    at this shared vertex.

    Example:
        edge 7 faces:  [1, 4]
        edge 15 faces: [8, 9]

        shared vertex 11 gets:

            BV11_CHAIN_E7_F1
            BV11_CHAIN_E7_F4
            BV11_CHAIN_E15_F8
            BV11_CHAIN_E15_F9
    """

    vertex_id = bevel_vertex.vertex_id
    selected_edges = list(bevel_vertex.selected_edges)

    if len(selected_edges) != 2:
        return []

    boundary_list = []

    for edge_id in selected_edges:
        edge_data = edge_data_by_id.get(edge_id)
        rails = rails_by_edge_id.get(edge_id, [])

        if edge_data is None:
            print("[BevelX] CHAIN_2 failed at vertex {0}: missing edge_data for edge {1}.".format(
                vertex_id,
                edge_id
            ))
            continue

        for rail_data in rails:
            face_id = rail_data["face_id"]

            point = get_rail_endpoint_for_vertex(
                edge_data=edge_data,
                rails=rails,
                face_id=face_id,
                vertex_id=vertex_id
            )

            if point is None:
                print(
                    "[BevelX] CHAIN_2 failed at vertex {0}: "
                    "missing rail endpoint for edge {1}, face {2}.".format(
                        vertex_id,
                        edge_id,
                        face_id
                    )
                )
                continue

            boundary_vertex = BX_BoundaryVertex(
                boundary_id="BV{0}_CHAIN_E{1}_F{2}".format(
                    vertex_id,
                    edge_id,
                    face_id
                ),
                original_vertex_id=vertex_id,
                selected_edge_id=edge_id,
                face_id=face_id,
                co_world=point,
                source="CHAIN_2"
            )

            boundary_list.append(boundary_vertex)

    link_boundary_vertices_cyclic(boundary_list)

    return boundary_list

def build_corner_2_boundary_for_vertex(bm,
                                       bevel_vertex,
                                       edge_data_by_id,
                                       rails_by_edge_id):
    """
    Build first sharp CORNER_2 boundary for a vertex touched by two selected edges.

    Current strategy:
        - Find the common face shared by both selected edges.
        - Find the non-common face on each selected edge.
        - Use rail endpoint on each non-common face.
        - Use line/line midpoint intersection of both rails on the common face.

    This is the first miter-style boundary for two connected selected edges.
    """

    vertex_id = bevel_vertex.vertex_id
    selected_edges = list(bevel_vertex.selected_edges)

    if len(selected_edges) != 2:
        return []

    edge_a_id = selected_edges[0]
    edge_b_id = selected_edges[1]

    edge_a = bm.edges[edge_a_id]
    edge_b = bm.edges[edge_b_id]

    common_faces = sorted(list(set(edge_a.faces).intersection(set(edge_b.faces))))

    if not common_faces:
        print("[BevelX] CORNER_2 failed at vertex {0}: no common face.".format(vertex_id))
        return []

    common_face_id = common_faces[0]

    outer_face_a = get_non_common_face(edge_a.faces, common_face_id)
    outer_face_b = get_non_common_face(edge_b.faces, common_face_id)

    if outer_face_a is None or outer_face_b is None:
        print("[BevelX] CORNER_2 failed at vertex {0}: missing outer faces.".format(vertex_id))
        return []

    edge_a_data = edge_data_by_id[edge_a_id]
    edge_b_data = edge_data_by_id[edge_b_id]

    rails_a = rails_by_edge_id[edge_a_id]
    rails_b = rails_by_edge_id[edge_b_id]

    point_outer_a = get_rail_endpoint_for_vertex(
        edge_data=edge_a_data,
        rails=rails_a,
        face_id=outer_face_a,
        vertex_id=vertex_id
    )

    point_outer_b = get_rail_endpoint_for_vertex(
        edge_data=edge_b_data,
        rails=rails_b,
        face_id=outer_face_b,
        vertex_id=vertex_id
    )

    point_common = get_common_face_miter_point(
        edge_a_data=edge_a_data,
        rails_a=rails_a,
        edge_b_data=edge_b_data,
        rails_b=rails_b,
        common_face_id=common_face_id
    )

    if point_outer_a is None or point_outer_b is None or point_common is None:
        print("[BevelX] CORNER_2 failed at vertex {0}: missing miter points.".format(vertex_id))
        return []

    boundary_list = [
        BX_BoundaryVertex(
            boundary_id="BV{0}_CORNER2_E{1}_F{2}".format(vertex_id, edge_a_id, outer_face_a),
            original_vertex_id=vertex_id,
            selected_edge_id=edge_a_id,
            face_id=outer_face_a,
            co_world=point_outer_a,
            source="CORNER_2"
        ),

        BX_BoundaryVertex(
            boundary_id="BV{0}_CORNER2_F{1}".format(vertex_id, common_face_id),
            original_vertex_id=vertex_id,
            selected_edge_id=edge_a_id,
            face_id=common_face_id,
            co_world=point_common,
            source="CORNER_2"
        ),

        BX_BoundaryVertex(
            boundary_id="BV{0}_CORNER2_E{1}_F{2}".format(vertex_id, edge_b_id, outer_face_b),
            original_vertex_id=vertex_id,
            selected_edge_id=edge_b_id,
            face_id=outer_face_b,
            co_world=point_outer_b,
            source="CORNER_2"
        ),
    ]

    link_boundary_vertices_cyclic(boundary_list)

    return boundary_list


def get_non_common_face(face_ids, common_face_id):
    """
    Return first face in face_ids that is not common_face_id.
    """

    for face_id in face_ids:
        if face_id != common_face_id:
            return face_id

    return None


def get_rail_endpoint_for_vertex(edge_data, rails, face_id, vertex_id):
    """
    Return the rail endpoint corresponding to vertex_id on face_id.
    """

    edge_v0, edge_v1 = edge_data["vertex_ids"]

    for rail_data in rails:
        if rail_data["face_id"] != face_id:
            continue

        rail_p0, rail_p1 = rail_data["rail"]

        if vertex_id == edge_v0:
            return rail_p0

        if vertex_id == edge_v1:
            return rail_p1

    return None


def get_rail_for_face(rails, face_id):
    """
    Return rail tuple for face_id.
    """

    for rail_data in rails:
        if rail_data["face_id"] == face_id:
            return rail_data["rail"]

    return None


def get_common_face_miter_point(edge_a_data,
                                rails_a,
                                edge_b_data,
                                rails_b,
                                common_face_id):
    """
    Return miter point on the common face between two selected edges.

    Uses closest point midpoint between the two common-face offset rails.
    """

    from BX_math import BX_math as bxm

    rail_a = get_rail_for_face(rails_a, common_face_id)
    rail_b = get_rail_for_face(rails_b, common_face_id)

    if rail_a is None or rail_b is None:
        return None

    a0, a1 = rail_a
    b0, b1 = rail_b

    return bxm.line_line_intersection_midpoint(
        a0,
        a1,
        b0,
        b1
    )